# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeProxyCommand < Formula
  desc "kube-proxyCommand use Kubernetes Pod port-forward as ssh ProxyCommand"
  homepage "https://github.com/ciiiii/kube-proxyCommand"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Darwin-arm64.tar.gz"
      sha256 "5de5fe6debf0511e96f0d723a1d265f5ae3265d0b1ec0b259829faa1ff089f84"

      def install
        if build.head?
          ldflags = %W[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Darwin-x86_64.tar.gz"
      sha256 "00e3b10b1ebde43b67eb85876d5da795dccbfa861608af405979f62c6e7ef835"

      def install
        if build.head?
          ldflags = %W[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Linux-x86_64.tar.gz"
      sha256 "3a96b9a8b853fcb2b94a0c562c7d462b2ec89a211c6c5e2d34726cc174e3216b"

      def install
        if build.head?
          ldflags = %W[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
  end

  head "https://github.com/ciiiii/kube-proxyCommand", branch: "master"
  head do
    depends_on "go" => :build
  end

  depends_on "go" => :optional
  depends_on "git"
end
