# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeProxyCommand < Formula
  desc "kube-proxyCommand use Kubernetes Pod port-forward as ssh ProxyCommand"
  homepage "https://github.com/ciiiii/kube-proxyCommand"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Darwin-x86_64.tar.gz"
      sha256 "9a5b3b9b413dfb79610ec02f76ec685699de6e0cd740fab473b10ac95fed273e"

      def install
        if build.head?
          ldflags = %@[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Darwin-arm64.tar.gz"
      sha256 "d6bf7a416d73728f03c7749cfc2a58156c2785e30a631116092bcad8ddd94d91"

      def install
        if build.head?
          ldflags = %@[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Linux-x86_64.tar.gz"
      sha256 "73052dd3c2a4ba994d15d2a43e29667889a2d9ef1179aa573f9c1885b70775c8"

      def install
        if build.head?
          ldflags = %@[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
  end

  head: "https://github.com/ciiiii/kube-proxyCommand", branch: "master"
  head do
    depends_on "go" => :build
  end

  depends_on "go" => :optional
  depends_on "git"
end
