# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeProxyCommand < Formula
  desc "kube-proxyCommand use Kubernetes Pod port-forward as ssh ProxyCommand"
  homepage "https://github.com/ciiiii/kube-proxyCommand"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Darwin-arm64.tar.gz"
      sha256 "a4a604e39af92cf5d4eeefa2b0949555b0d67c7b34c36c1b24d67e0dfe590e13"

      def install
        if build.head?
          ldflags = %W[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Darwin-x86_64.tar.gz"
      sha256 "78548b6fd73504ebdd377b46f0a104667bd3f5876cbeaf35f2b5ba8683dbe296"

      def install
        if build.head?
          ldflags = %W[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ciiiii/kube-proxyCommand/releases/download/v0.1.0/kube-proxyCommand_0.1.0_Linux-x86_64.tar.gz"
      sha256 "bd19bef64a98e59481c485e717f2751d7bc3f926394e34c197fb16f1b3668cb7"

      def install
        if build.head?
          ldflags = %W[
            -s -w
          ]
          system "go", "build", *std_go_args(output: "kube-proxyCommand", ldflags: ldflags.join(" ")), "main.go"
        end
        bin.install "kube-proxyCommand"
      end
    end
  end

  head: "https://github.com/ciiiii/kube-proxyCommand", branch: "master"
  head do
    depends_on "go" => :build
  end

  depends_on "go" => :optional
  depends_on "git"
end
